default:
  db: dev_sqlite
  llm: openai_prod
db_connections:
  dev_sqlite:
    type: sqlite
    path: demo.db
llm_providers:
  openai_prod:
    provider: openai
    model: gpt-3.5-turbo
output_profiles:
  my_markdown:
    type: markdown
    output_filename: catalog.md
