default:
  db: local_sqlite
  llm: local_ollama

db_connections:
  local_sqlite:
    type: "sqlite"     
    path: "test.db"    

  dev_postgres:
    type: "postgres"
    host: "localhost"
    port: 5432
    user: "admin"
    password: "password"
    dbname: "analytics_db"

llm_providers:
  openai_prod:
    provider: "openai"  
    model: "gpt-4o-mini"

  local_ollama:
    provider: "ollama"
    model: "granite3.3:2b"
    host: "http://localhost:11434"